name: ci-sonar

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  sonarcloud:
    uses: ./.github/workflows/sonarcloud-module.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
