name: SonarCloud Analysis

on:
  workflow_call:
    inputs:
      UBUNTU_VERSION:
        default: 'ubuntu-latest'
        required: false
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

permissions:
  pull-requests: read

jobs:
  sonarcloud:
    name: Run SonarCloud Analysis
    runs-on: ${{ inputs.UBUNTU_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4b4d7634dab97dcee0b75763a54a6dc92a9e6bc1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
